# Usa una imagen base de Ubuntu
FROM ubuntu:latest

# Configura el entorno para evitar la interactividad
ENV DEBIAN_FRONTEND=noninteractive

# Actualiza el sistema e instala las dependencias necesarias
RUN apt-get update \
    && apt-get install -y php libapache2-mod-php \
    && apt-get install -y composer \
    && apt-get install -y systemctl \
    && apt-get install -y vim \
    && apt-get install -y apache2 \
    && apt-get install -y php-xml \
    && apt-get install -y git \
    && apt install -y php-curl \
    && apt-get install -y php-pgsql \
    && apt-get clean \
    && service apache2 restart \
    && rm -rf /var/lib/apt/lists/*

# Clona el proyecto desde GitHub
RUN  cd var/www/html 

WORKDIR /var/www/html/Laravel-docker

COPY mi-sitio.conf /etc/apache2/sites-available
COPY apache2.conf /etc/apache2

#Deshabilitar el archivo default de la configuración de apache2
RUN a2dissite 000-default.conf \
    #Das permisos al usuario de apache 2 a la configuración
    && chown -R www-data:www-data /etc/apache2/sites-available/mi-sitio.conf \
    # permite crear direcciones URL alternativas a las dinámicas generadas por la programación de nuestro sitio web
    && a2enmod rewrite \
    #Aplica las configuraciones para mi-sitio
    && a2ensite mi-sitio.conf \
    && systemctl restart apache2  
    
# Expone el puerto 80 (o el puerto que necesites)
EXPOSE 80

# Comando para iniciar apache y que se mantenga abierto el contenedor
CMD cd /var/www/html/Laravel-docker/example-app \
    && composer install \
    && chown -R www-data:www-data /var/www/html/Laravel-docker/example-app/storage \
    && chown -R www-data:www-data /var/www/html/Laravel-docker/example-app/bootstrap/cache \
    && cd /var/www/html/Laravel-docker/example-app/ \
    && php artisan key:generate \
    && systemctl start apache2 \
    && tail -f /dev/null
